#!/bin/bash
# ./generate-module.sh

rm -fr spec*
# For personal scripts
mkdir utilities/
# Get the script to connect to docker provider
wget -O utilities/kl.sh https://gist.github.com/jecnua/86e1495c6e9367504829d62a3af6dcca/raw/
chmod 700 utilities/kl.sh
# Delete reports
echo "rm -fr test/reports/*.html" > utilities/delete_reports.sh
chmod 700 utilities/delete_reports.sh
# Creating default puppetfile
librarian-puppet init
bundle init
# Get the default gemfile
wget -O Gemfile https://gist.githubusercontent.com/jecnua/235ba3a90182da2ea9094a263f2e55e7/raw/Gemfile
# Get the default .gitignore
wget -O .gitignore https://gist.github.com/jecnua/50c8f260c59a3d27d20c5eeed1bee468/raw/
#
bundle install
kitchen init
# Download override example
wget -O _RENAME_ME_.kitchen.local.yml https://gist.github.com/jecnua/005b432fc0cb7bbdbcf37dd6a060d5e8/raw/
# Get the default kitchen.yml
wget -O .kitchen.yml https://gist.githubusercontent.com/jecnua/235ba3a90182da2ea9094a263f2e55e7/raw/.kitchen.yml
# Rubocop
wget -O .rubocop.yml https://gist.githubusercontent.com/jecnua/235ba3a90182da2ea9094a263f2e55e7/raw/.rubocop.yml
# Travis
wget -O .travis.yml https://gist.githubusercontent.com/jecnua/235ba3a90182da2ea9094a263f2e55e7/raw/.travis.yml

# Adding simple test in default test dir
echo "class {'::$NAME':}" >> test/default.pp
mkdir test/reports
mkdir test/integration/default/serverspec/
mkdir test/integration/default/serverspec/default/
# Get spec helper
wget -O test/integration/default/serverspec/spec_helper.rb https://gist.github.com/jecnua/788748542498a3ebf11b3ad025ee56fa/raw/
# Get localhost test
wget -O test/integration/default/serverspec/default/default_spec.rb https://gist.github.com/jecnua/004f45df291bfd8e86e72556f22ae0ab/raw/

# Fix the Puppetfile, rakefile, and so on
rake rubocop:auto_correct

time kitchen converge
time kitchen verify
time rake validate
time rake rubocop

echo "DONE"
